### ISSUE TITLE
编辑多边形模式

### ISSUE THREAD

**Issue by ybxbupt** [beichen2012/LabelMe#2]
在您的程序中，“在编辑多边形模式下，可以点击图片中的多边形，选中的会变成红色，此时可以删除它”
能否改成像labelme一样可以编辑多边形的端点？
如果我想改成可以编辑多边形的端点，当前程序没有实现这个功能，主要困难是什么？

**Comment by beichen2012** [comment]
1，如果是在创建多边形时，有的点选错了，此时可以使用ESC键撤销上 一个点的选取（按n次就会撤销上n次选取的点）。
2，目前在编辑多边形的模式下，只实现了删除功能。主要困难是没时间。如果您方便，欢迎添加此功能，欢迎发起PR。
谢谢。
