### ISSUE TITLE
unresolved external symbol

### ISSUE THREAD

**Issue by newforrestgump001** [beichen2012/LabelMe#4]
1>LabelMeWinDlg.obj : error LNK2001: unresolved external symbol __imp_DestroyDiReaderObj
1>LabelMeWinDlg.obj : error LNK2001: unresolved external symbol __imp_GetDiReaderObj
1>LabelMeWinDlg.obj : error LNK2001: unresolved external symbol __imp_ReleaseDiImage
1>D:\opensource\LabelMe\x64\Release\LabelMeWin.exe : fatal error LNK1120: 3 unresolved externals

**Comment by beichen2012** [comment]
dcm lib only support x86

**Comment by newforrestgump001** [comment]
@beichen2012 , Thank you for your information!

**Comment by dlml** [comment]
@beichen2012  我在win上release x64编译，也出现这个问题 ，怎么解决呢？
